# todo: insert HRF as code
# try using aside as class instead of html 
# NOTE: set to "book" for website or "default" for rendering individual documents
project:
  type: book
  output-dir: docs

book:
  title: "Advanced Neuroimaging"
  subtitle: "PSY.842"
  author: "Natalia Zaretskaya"
  date: "2026"
  date-format: "SS YYYY"
  chapters:
    - index.qmd
    - syllabus.qmd
    - overview.qmd
    - fmri-intro.qmd
    - planning.qmd
    - paradigm.qmd
    - data-management.qmd
    - preprocessing.qmd
    - glm.qmd

format:
  html:
    theme: cosmo
    number-depth: 0
    code-fold: true
  revealjs:
    theme: [clean.scss]
    auto-stretch: false
    incremental: true
    scrollable: true
    slide-number: true
    chalkboard: true
    code-fold: true
#    footer: "Natlaia Zaretskaya - Neuroimaging 2026"
    width: 1600          # slide width in px
    height: 900          # slide height in px
    margin: 0.05         # reduce margins (default 0.05 = 5%)
#  typst: 
#    toc: false
#    columns: 1
#    number-sections: false
  pdf:
    documentclass: report
    code-overflow: wrap

quarto:
  crossref: true
  
metadata:
  email: "natalia.zaretskaya@uni-graz.at"

bibliography: references.bib
  
editor: visual
